name: Azure Functions Python CI/CD

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Match your Azure Function Python version

      # Optional: Install dependencies locally for linting/tests
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # Optional: Run tests here if you have tests

      - name: Publish to Azure Functions with remote build
        uses: Azure/functions-action@v1
        with:
          app-name: Ledgeremail-gitTest  # <-- Your Azure Function App name (no angle brackets)
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: .
          scm-do-build-during-deployment: true # This triggers remote build, ensuring requirements.txt is installed